# -*- coding: utf-8 -*-
"""CASOS PRÁCTICOS - CIENCIA DE DATOS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJA6AK9c3b_TXoZjEsbVCL5_Gz1ajMlm
"""

import pandas as pd

datos = {
    "estudiante": ["Ana", "Luis", "Carlos", "Maria", "Pedro",
                   "Lucia", "Jose", "Sofia"],
    "asistencia": [95, 70, 85, 90, 55, 80, 60, 98],
    "nota": [18, 12, 15, 17, 9, 14, 10, 19]
}

df = pd.DataFrame(datos)

print(df)

print(df.head())
print(df.info())
print(df.describe())

print(df.head())

print(df.info())

print(df.describe())

"""Promedio : .mean() es un método en Pandas que se utiliza para calcular la media aritmética (el promedio) de un conjunto de datos."""

promedio = df["nota"].mean()

print("Promedio:", promedio)

"""
Nota máxima y mínima

"""

print("Nota máxima:", df["nota"].max())
print("Nota mínima:", df["nota"].min())

Estudiantes aprobados

Supongamos que la nota mínima aprobatoria es 11.

aprobados = df[df["nota"] >= 11]

print(aprobados)

"""Estudiantes en riesgo"""

riesgo = df[(df["nota"] < 11) | (df["asistencia"] < 70)]

print("Estudiantes en riesgo:")
print(riesgo)

import matplotlib.pyplot as plt

plt.scatter(df["asistencia"], df["nota"])

plt.xlabel("Asistencia (%)")
plt.ylabel("Nota")
plt.title("Relación entre asistencia y nota")

plt.show()

"""**Caso práctico 2: Limpieza de datos**

Este caso sirve para explicar una parte fundamental del ciclo de vida de los datos.

Tenemos datos incorrectos: *texto en cursiva*
"""

import pandas as pd
import numpy as np

datos = {
    "estudiante": ["Ana", "Luis", "Carlos", "Maria", "Pedro", "Ana"],
    "edad": [20, 21, np.nan, 22, 200, 20],
    "nota": [18, 15, np.nan, 17, 9, 18],
    "asistencia": [95, 80, 85, np.nan, 55, 95]
}

df = pd.DataFrame(datos)

print(df)

"""**Detectar valores faltantes**"""

print(df.isnull().sum())

"""**Eliminar duplicados**"""

df = df.drop_duplicates()

print(df)

"""**Corregir edad**

Una edad de 200 años es evidentemente incorrecta.
"""

df.loc[df["edad"] > 100, "edad"] = np.nan

df = df.drop_duplicates()

print(df)

"""**Caso práctico 3: Predicción de ventas**
Este caso permite explicar regresión.

Problema

Una tienda quiere predecir sus ventas.

Datos: *texto en cursiva*
"""

import pandas as pd

datos = {
    "publicidad": [100, 200, 300, 400, 500,
                   600, 700, 800, 900, 1000],

    "ventas": [1200, 1800, 2500, 3200, 3900,
               4500, 5200, 6000, 6700, 7500]
}

df = pd.DataFrame(datos)

print(df)

"""Visualizar"""

import matplotlib.pyplot as plt

plt.scatter(
    df["publicidad"],
    df["ventas"]
)

plt.xlabel("Inversión en publicidad")
plt.ylabel("Ventas")
plt.title("Publicidad vs Ventas")

plt.show()

"""Crear **modelo**"""

from sklearn.linear_model import LinearRegression

X = df[["publicidad"]]
y = df["ventas"]

modelo = LinearRegression()

modelo.fit(X, y)

"""Predicción

Supongamos que invertiremos S/ 1,200 en publicidad:
"""

prediccion = modelo.predict([[1200]])

print("Ventas estimadas:", prediccion[0])